# Generated by Django 6.0.1 on 2026-04-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogcategory_blogpost_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog/posts/videos/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(max_length=250),
        ),
    ]
