# Generated by Django 6.0.1 on 2026-04-22 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('food', 'Food & Restaurant'), ('fashion', 'Fashion & Clothing'), ('health', 'Health & Beauty'), ('tech', 'Technology & IT'), ('education', 'Education & Training'), ('construction', 'Construction & Real Estate'), ('finance', 'Finance & Investment'), ('transport', 'Transport & Logistics'), ('retail', 'Retail & Shopping'), ('hospitality', 'Hospitality & Events'), ('agriculture', 'Agriculture & Farming'), ('media', 'Media & Entertainment'), ('legal', 'Legal & Professional'), ('worship', 'Church & Religious'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='businesses/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='businesses/banners/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True, max_length=300)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
