# Generated by Django 6.0.1 on 2026-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Restaurants'), ('fashion', 'Fashion & Clothing'), ('health', 'Health & Beauty'), ('tech', 'Technology & IT'), ('education', 'Education & Training'), ('construction', 'Construction & Real Estate'), ('finance', 'Finance & Investment'), ('transport', 'Transport & Logistics'), ('retail', 'Retail & Shopping'), ('hospitality', 'Hospitality & Events'), ('agriculture', 'Agriculture & Farming'), ('media', 'Media & Entertainment'), ('legal', 'Legal & Professional'), ('worship', 'Church & Religious'), ('other', 'Other')], max_length=50),
        ),
    ]
