# Generated by Django 6.0.1 on 2026-04-22 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('branch', models.CharField(blank=True, choices=[('', 'Select Branch'), ('headquarters', 'TREM Headquarters'), ('lagos_island', 'Lagos Island'), ('victoria_island', 'Victoria Island'), ('lekki', 'Lekki'), ('surulere', 'Surulere'), ('ikeja', 'Ikeja'), ('abuja', 'Abuja'), ('port_harcourt', 'Port Harcourt'), ('ibadan', 'Ibadan'), ('other', 'Other Branch')], max_length=50)),
                ('unit', models.CharField(blank=True, choices=[('', 'Select Unit'), ('choir', 'Choir'), ('ushering', 'Ushering'), ('prayer', 'Prayer Warriors'), ('media', 'Media & Tech'), ('children', "Children's Ministry"), ('youth', 'Youth Ministry'), ('women', "Women's Ministry"), ('men', "Men's Ministry"), ('evangelism', 'Evangelism'), ('welfare', 'Welfare'), ('general', 'General Member')], max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('date_joined_church', models.DateField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
